version: '2'

services:
  jenkins:
    image: jenkins/jenkins:2.111
    volumes:
      - ./jenkins_home/:/var/jenkins_home/
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_net

networks:
  jenkins_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.99.0/24
        gateway: 192.168.99.1
